
Citizen.CreateThread(function()
    while true do
        SetWeaponDamageModifier(`weapon_unarmed`, 1.0) -- Weapon Label (Fists)	
        SetWeaponDamageModifier(`weapon_dagger`, 1.0) -- Weapon Label (Dagger)	
        SetWeaponDamageModifier(`weapon_bat`, 1.0) -- Weapon Label (Bat)	
        SetWeaponDamageModifier(`weapon_bottle`, 1.0) -- Weapon Label (Broken Bottle)	
        SetWeaponDamageModifier(`weapon_crowbar`, 1.0) -- Weapon Label (Crowbar)	
        SetWeaponDamageModifier(`weapon_flashlight`, 1.0) -- Weapon Label (Flashlight)	
        SetWeaponDamageModifier(`weapon_golfclub`, 1.0) -- Weapon Label (Golfclub)	
        SetWeaponDamageModifier(`weapon_hammer`, 1.0) -- Weapon Label (Hammer)	
        SetWeaponDamageModifier(`weapon_hatchet`, 1.0) -- Weapon Label (Hatchet)	
        SetWeaponDamageModifier(`weapon_knuckle`, 1.0) -- Weapon Label (Knuckle)	
        SetWeaponDamageModifier(`weapon_knife`, 1.0) -- Weapon Label (Knife)	
        SetWeaponDamageModifier(`weapon_machete`, 1.0) -- Weapon Label (Machete)	
        SetWeaponDamageModifier(`weapon_switchblade`, 1.0) -- Weapon Label (Switchblade)	
        SetWeaponDamageModifier(`weapon_nightstick`, 1.0) -- Weapon Label (Nightstick)	
        SetWeaponDamageModifier(`weapon_wrench`, 1.0) -- Weapon Label (Wrench)	
        SetWeaponDamageModifier(`weapon_battleaxe`, 1.0) -- Weapon Label (Battle Axe)	
        SetWeaponDamageModifier(`weapon_poolcue`, 1.0) -- Weapon Label (Poolcue)
        SetWeaponDamageModifier(`weapon_stone_hatchet`, 1.0) -- Weapon Label (Stone Hatchet)	
	Wait(0)
    end
end)
